main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('shoes/', views.shoes_index, name='index'),
  path('shoes/<int:shoe_id>/', views.shoes_detail, name='detail'),
  path('shoes/create/', views.ShoeCreate.as_view(), name='shoes_create'),
  path('shoes/<int:pk>/update/', views.ShoeUpdate.as_view(), name='shoes_update'),
  path('shoes/<int:pk>/delete/', views.ShoeDelete.as_view(), name='shoes_delete'),
  path('shoes/<int:shoe_id>/add_wore/', views.add_wore, name='add_wore'),
  path('shoes/<int:shoe_id>/assoc_occasion/<int:occasion_id>/', views.assoc_occasion, name='assoc_occasion'),
  path('shoes/<int:shoe_id>/unassoc_occasion/<int:occasion_id>/', views.unassoc_occasion, name='unassoc_occasion'),
  path('shoes/<int:shoe_id>/add_photo/', views.add_photo, name='add_photo'),
  path('occasions/', views.OccasionList.as_view(), name='occasions_index'),
  path('occasions/<int:pk>/', views.OccasionDetail.as_view(), name='occasions_detail'),
  path('occasions/create/', views.OccasionCreate.as_view(), name='occasions_create'),
  path('occasions/<int:pk>/update/', views.OccasionUpdate.as_view(), name='occasions_update'),
  path('occasions/<int:pk>/delete/', views.OccasionDelete.as_view(), name='occasions_delete'),
  path('accounts/signup/', views.signup, name='signup'),
]

shoecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

STATUS = (
    ('W', 'Wore Shoe'),
    ('N', "Not Worn"),
    ('P', 'Plan to wear'),
)

# Create your models here.
class Occasion(models.Model):
  name = models.CharField(max_length=50)
  activity = models.CharField(max_length=100)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('occasions_detail', kwargs={'pk': self.id})


class Shoe(models.Model):
  name = models.CharField(max_length=100)
  brand = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  gender = models.CharField(max_length=100)
  size = models.IntegerField()
  color = models.CharField(max_length=100)
  price = models.CharField(max_length=100)
  # add a M:M assoc between shoes & occasions
  occasions = models.ManyToManyField(Occasion)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.name} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'shoe_id': self.id})

  def wore_status(self):
    return self.wore_set.filter(date=date.today()).count() >= len(STATUS[0][0])

class Wore(models.Model):
  date = models.DateField('Shoe Status Date')
  status = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=STATUS,
    # set the default value for status to be 'O'
    default=STATUS[0][0]
  )

  # Create a shoe_id FK
  shoe = models.ForeignKey(
    Shoe, 
    on_delete=models.CASCADE
  )

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_status_display()} on {self.date}"
    # status used to be meal
    # might cause error

  class Meta:
    ordering = ['-date']

class Photo(models.Model):
  url = models.CharField(max_length=200)
  shoe = models.ForeignKey(Shoe, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for shoe_id: {self.shoe_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Wore

class WoreForm(ModelForm):
  class Meta:
    model = Wore
    fields = ['date', 'status']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import os
import uuid
import boto3
from .models import Shoe, Occasion, Photo
from .forms import WoreForm

# Create your views here.

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def shoes_index(request):
  shoes = Shoe.objects.filter(user=request.user)
  return render(request, 'shoes/index.html', {'shoes': shoes})

@login_required
def shoes_detail(request, shoe_id):
  shoe = Shoe.objects.get(id=shoe_id)
  id_list = shoe.occasions.all().values_list('id')
  occasions_shoe_doesnt_have = Occasion.objects.exclude(id__in=id_list)
  wore_form = WoreForm()
  return render(request, 'shoes/detail.html', {
    'shoe': shoe,
    'wore_form': wore_form,
    'occasions': occasions_shoe_doesnt_have
  })
  
class ShoeCreate(LoginRequiredMixin, CreateView):
  model = Shoe
  fields = ['name', 'brand', 'description', 'gender', 'size', 'color', 'price']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class ShoeUpdate(LoginRequiredMixin, UpdateView):
  model = Shoe
  # Let's disallow the renaming of a Shoe by excluding the name field!
  fields = ['brand', 'description', 'gender', 'size', 'color', 'price']

class ShoeDelete(LoginRequiredMixin, DeleteView):
  model = Shoe
  success_url = '/shoes/'

@login_required
def add_wore(request, shoe_id):
  form = WoreForm(request.POST)
  if form.is_valid():
    new_wore = form.save(commit=False)
    new_wore.shoe_id = shoe_id
    new_wore.save()
  return redirect('detail', shoe_id=shoe_id)

@login_required
def assoc_occasion(request, shoe_id, occasion_id):
  Shoe.objects.get(id=shoe_id).occasions.add(occasion_id)
  return redirect('detail', shoe_id=shoe_id)

@login_required
def unassoc_occasion(request, shoe_id, occasion_id):
  Shoe.objects.get(id=shoe_id).occasions.remove(occasion_id)
  return redirect('detail', shoe_id=shoe_id)

class OccasionList(LoginRequiredMixin, ListView):
  model = Occasion

class OccasionDetail(LoginRequiredMixin, DetailView):
  model = Occasion

class OccasionCreate(LoginRequiredMixin, CreateView):
  model = Occasion
  fields = '__all__'

class OccasionUpdate(LoginRequiredMixin, UpdateView):
  model = Occasion
  fields = ['name', 'color']

class OccasionDelete(LoginRequiredMixin, DeleteView):
  model = Occasion
  success_url = '/occasions/'

@login_required
def add_photo(request, shoe_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, shoe_id=shoe_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
  return redirect('detail', shoe_id=shoe_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # Save the user to the db
      user = form.save()
      # Programmatically login
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About</h1>
<hr>
<p>Track and organize your shoe collection! Plan out your style ahead of time.</p>
<h4>Contact:</h4>
  <a href="https://github.com/jctgarcia20">GitHub</a>
  <br>
  <a href="https://www.linkedin.com/in/jctgarcia20/">LinkedIn</a>
  <br>
  <a href="jctgarcia20@gmail.com">Contact</a>
  <br>
  <br>
<footer>All Rights Reserved, &copy; 2022 Jordan-Christopher T. Garcia</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Shoe Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="brand-logo center black-text" id="logo">&nbsp;&nbsp;ShoeCollector</a></li>
        </ul>
        <br>
        <ul class="brand-logo center">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'occasions_create' %}">Add an Occasion</a></li>
            <li><a href="{% url 'occasions_index' %}">View All Occasions</a></li>
            <li><a href="{% url 'shoes_create' %}">Add a Shoe</a></li>
            <li><a href="{% url 'index' %}">View All My Shoes</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Jordan-Christopher T. Garcia &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<br>
<h1 id="slogan">Start Your Collection</h1>
<img src="https://i.imgur.com/QPcuuca.png" alt="air jordan 1" id="homeImg">
<a href="shoes/create/" class="waves-effect waves-light btn grey lighten-2 black-text" id="homeBtn">Begin Collecting</a>

{% endblock %}

main_app/templates/main_app/occasion_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Occasion</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'occasions_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/occasion_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Occasion Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ occasion.name }}</span>
        <p>Activity: {{ occasion.activity }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'occasions_update' occasion.id %}">Edit</a>
        <a href="{% url 'occasions_delete' occasion.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/occasion_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Occasion</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <br>
    <input type="submit" value="Add Occasion" class="btn red lighten-2">
  </form>
{% endblock %}

main_app/templates/main_app/occasion_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Occasion List</h1>

{% for occasion in occasion_list %}
  <a href="{% url 'occasions_detail' occasion.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ occasion.name }}</span>
            <p>Activity: {{ occasion.activity }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/shoe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Shoe</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' shoe.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/shoe_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
  <h1>Add Shoe</h1>
{% endif %}

<!-- empty action attribute will post to the same url in the address bar -->
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br>
  <input type="submit" value="Add Shoe" class="btn red lighten-2">
</form>

{% endblock %}

main_app/templates/shoes/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Shoe Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ shoe.name }}</span>
        <p>Name: {{ shoe.name }}</p>
        <p>Brand: {{ shoe.brand }}</p>
        <p>Description: {{ shoe.description }}</p>
        <p>Gender: {{ shoe.gender }}</p>
        <p>Size: {{ shoe.size }}</p>
        <p>Color: {{ shoe.color }}</p>
        <p>Price: {{ shoe.price }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'shoes_update' shoe.id %}">Edit</a>
        <a href="{% url 'shoes_delete' shoe.id %}">Delete</a>
      </div>
    </div>
    {% for photo in shoe.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}" alt="shoe photo">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' shoe.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn grey" value="Upload Photo">
    </form>  
  </div>
  <div class="col s6">
    <form action="{% url 'add_wore' shoe.id %}" method="POST">
      {% csrf_token %}
      {{ wore_form.as_p }}
      <input type="submit" class="btn btn grey" value="Add to Collection">
    </form>
    <br>
    {% if shoe.wore_status %}
      <div class="card-panel teal-text center-align">{{shoe.name}} status is up to date</div>
    {% else %}
      <div class="card-panel red-text center-align">{{shoe.name}} has no status in your collection</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Shoe Status</th></tr>
      </thead>
      <tbody>
        {% for wore in shoe.wore_set.all %}
          <tr>
            <td>{{wore.date}}</td>
            <td>{{wore.get_status_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ shoe.name }}'s Occasions</h3>
    {% if shoe.occasions.count %}
      {% for occasion in shoe.occasions.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="activity: {{ occasion.activity }}">{{ occasion.activity }}</span> 
              <br>
              Activity: {{ occasion.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_occasion' shoe.id occasion.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn grey">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Occasions :(</h5>
    {% endif %}
  </div>
  <!-- Available occasions will come after this line -->
  <div class="col s6">
    <h3>Available Occasions</h3>
    {% if occasions.count %}
      {% for occasion in occasions.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span style="activity: {{ occasion.activity }}">{{ occasion.activity }}</span> 
              <br>
              Activity: {{ occasion.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_occasion' shoe.id occasion.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn grey">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{shoe.name}} Already Has All Occasions Available</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_status');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/shoes/index.html
{% extends 'base.html' %}
{% block content %}

<h1>All My Shoes</h1>

{% for shoe in shoes %}
  <div class="card">
    <a href="{% url 'detail' shoe.id %}">
      <div class="card-content">
        <span class="card-title">{{ shoe.name }}</span>
        <p>Name: {{ shoe.name }}</p>
        <p>Brand: {{ shoe.brand }}</p>
        <p>Description: {{ shoe.description }}</p>
        <p>Gender: {{ shoe.gender }}</p>
        <p>Size: {{ shoe.size }}</p>
        <p>Color: {{ shoe.color }}</p>
        <p>Price: {{ shoe.price }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}